"""add customer phone

Revision ID: 1dd1c5cbc774
Revises: e5db8004e0ba
Create Date: 2026-10-08 22:55:27.424541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd1c5cbc774'
down_revision: Union[str, Sequence[str], None] = 'e5db8004e0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.create_unique_constraint('customers_phone_key', 'customers', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customers_phone_key', 'customers', type_='unique')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
